name: video_behavior_analyzer
description: Aplicaci칩n para an치lisis de comportamiento mediante visi칩n por computadora

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  # C치mara y video
  camera: ^0.11.2
  video_player: ^2.8.1
  image_picker: ^1.0.4
  
  # ML y procesamiento
  tflite_flutter: ^0.11.0
  image: ^4.1.3
  
  # Almacenamiento


  
  # Permisos
  permission_handler: ^12.0.1
  
  
  get: ^4.6.6
  flutter_speed_dial: ^7.0.0
  percent_indicator: ^4.2.3
  
  # HTTP para modelos
  dio: ^5.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.2.0
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true  
  assets:
    - assets/models/
    - assets/images/
  