name: video_behavior_analyzer
description: Aplicación para análisis de comportamiento mediante visión por computadora

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Cámara y video
  camera: ^0.10.5+5
  video_player: ^2.8.1
  image_picker: ^1.0.4
  
  # ML y procesamiento (versión compatible)
  tflite_flutter: ^0.10.4
  image: ^4.1.3
  
  # Almacenamiento
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Permisos
  permission_handler: ^11.1.0
  
  # UI y navegación
  get: ^4.6.6
  flutter_speed_dial: ^7.0.0
  percent_indicator: ^4.2.3
  
  # HTTP
  dio: ^5.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true  
  assets:
    - assets/models/