name: agrobot_ec
description: "Aplicación móvil con chatbot inteligente para agricultores ecuatorianos"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^12.1.3

  # HTTP & WebSocket
  dio: ^5.4.0
  web_socket_channel: ^2.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Location
  geolocator: ^10.1.0

  # Voice
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  permission_handler: ^11.1.0

  # Utils
  intl: ^0.19.0
  equatable: ^2.0.5
  http: ^1.4.0

  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/crops/
    - assets/images/icons/
    - assets/images/illustrations/