// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU6Y5jb_kCdvNFW7a21xYp7AGrjeu2fWM',
    appId: '1:582901680582:web:a9b898baae779dfa67cac7',
    messagingSenderId: '582901680582',
    projectId: 'crudestudiantes-4b379',
    authDomain: 'crudestudiantes-4b379.firebaseapp.com',
    storageBucket: 'crudestudiantes-4b379.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcMDAfoDwE_-htxyJ1u8L_828zjFFTs0I',
    appId: '1:582901680582:android:9346eeb597cff16e67cac7',
    messagingSenderId: '582901680582',
    projectId: 'crudestudiantes-4b379',
    storageBucket: 'crudestudiantes-4b379.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC09YtGn-7w7Z7mVT3h8hwOtAAX2xV-Ojw',
    appId: '1:582901680582:ios:2b54589e6224ce2c67cac7',
    messagingSenderId: '582901680582',
    projectId: 'crudestudiantes-4b379',
    storageBucket: 'crudestudiantes-4b379.firebasestorage.app',
    iosBundleId: 'com.example.pryCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC09YtGn-7w7Z7mVT3h8hwOtAAX2xV-Ojw',
    appId: '1:582901680582:ios:2b54589e6224ce2c67cac7',
    messagingSenderId: '582901680582',
    projectId: 'crudestudiantes-4b379',
    storageBucket: 'crudestudiantes-4b379.firebasestorage.app',
    iosBundleId: 'com.example.pryCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU6Y5jb_kCdvNFW7a21xYp7AGrjeu2fWM',
    appId: '1:582901680582:web:f8148ba9d4e6694d67cac7',
    messagingSenderId: '582901680582',
    projectId: 'crudestudiantes-4b379',
    authDomain: 'crudestudiantes-4b379.firebaseapp.com',
    storageBucket: 'crudestudiantes-4b379.firebasestorage.app',
  );
}
